serve:

  port:

    # The localhost port that target files should be served on.
    target:      9000

    # The localhost port to serve documentation on.
    docs:        9090


# Build paths. All paths should be relative to the project root.
path:

  coverage:     coverage

  tools:        tools

  # Source file directory.
  src:          src

  # Tests directory.
  test:         test

  # Output target directories.
  target:       .

  # Generated documentation glob.
  doc:          docs



# Environment build options.
env:

  # The common options are set initially, then overridden by each environment
  # as necessary.
  default:

    # Webpack options.
    webpack:
      entry:        bootstrap.coffee
      output:
        pathinfo:   true
        publicPath: /

    # Webpack UglifyJS plugin options.
    # @see http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
    uglify:
      compress:
        warnings: false
      sourceMap: false


  # Production specific options.
  production:

    # Webpack options.
    webpack:
      output:
        pathinfo:   false
        publicPath: http://yourcdn.com/


  # Test-build configuration. Used for unit-testing.
  test:

    # Webpack test build options. Entry point is resolved from
    # `path.test.unit.coffee` build option.
    webpack:
      entry:        test-bootstrap.coffee


  # Debug (development) options.
  debug:

    # Enable sourcemap output.
    uglify:
      sourceMap: true
